BasvuruTakip/Controllers/PersonelIsBasvurusuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BasvuruTakip.Data;
using BasvuruTakip.Models;

namespace BasvuruTakip.Controllers
{
    public class PersonelIsBasvurusuController : Controller
    {
        private readonly AppDbContext _context;
        public PersonelIsBasvurusuController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Create()
        {
            ViewBag.Iller = new SelectList(_context.Iller.OrderBy(i => i.Adi), "Id", "Adi");
            ViewBag.Personeller = new SelectList(_context.Personeller, "Id", "AdiSoyadi");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonelIsBasvurusu basvuru)
        {
            basvuru.BasvuruTarihi = DateTime.SpecifyKind(basvuru.BasvuruTarihi, DateTimeKind.Utc);
            if (ModelState.IsValid)
            {
                _context.PersonelIsBasvurulari.Add(basvuru);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create");
            }
            ViewBag.Iller = new SelectList(_context.Iller.OrderBy(i => i.Adi), "Id", "Adi");
            ViewBag.Personeller = new SelectList(_context.Personeller, "Id", "AdiSoyadi");
            return View(basvuru);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var basvuru = await _context.PersonelIsBasvurulari.FindAsync(id);
            if (basvuru != null)
            {
                _context.PersonelIsBasvurulari.Remove(basvuru);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Listele"); 
        }
        public JsonResult GetIlceler(long ilId)
        {
            var ilceler = _context.Ilceler
                .Where(i => i.IlId == ilId)
                .Select(i => new { i.IlceId, i.Adi })
                .ToList();
            return Json(ilceler);
        }



        //*------------------------------



        public IActionResult Listele()
        {
            if (HttpContext.Session.GetString("YetkiliMi") != "evet")
            {
                return RedirectToAction("Giris", "Yetkili");
            }

            ViewBag.Personeller = new SelectList(_context.Personeller.OrderBy(p => p.AdiSoyadi), "Id", "AdiSoyadi");
            return View();
        }
        public JsonResult GetBasvurular(long personelId)
        {
            var basvurular = _context.PersonelIsBasvurulari
                .Where(b => b.PersonelId == personelId)
                .Select(b => new
                {
                    Id = b.Id,

                    Tarih = b.BasvuruTarihi.ToString("dd.MM.yyyy"),
                    Il = _context.Iller.FirstOrDefault(i => i.Id == b.IlId)!.Adi,
                    Seyahat = b.SeyahatEngeliYok ? "Yok" : "Var",
                    b.IsyeriAdi,
                    b.Pozisyon,
                    b.Aciklama
                }).ToList();
            return Json(basvurular);
        }
        public JsonResult GetPersonelBilgi(long personelId)
        {
            var personel = _context.Personeller
                .Where(p => p.Id == personelId)
                .Select(p => new
                {
                    p.AdiSoyadi,
                    p.Cinsiyet,
                    DogumTarihi = p.DogumTarihi.ToString("dd.MM.yyyy"),
                    Il = _context.Iller.FirstOrDefault(i => i.Id == p.IlId)!.Adi,
                    Ilce = _context.Ilceler.FirstOrDefault(il => il.IlceId == p.IlceId && il.IlId == p.IlId)!.Adi,
                    p.Aciklama
                }).FirstOrDefault();

            return Json(personel);
        }









    }
}

BasvuruTakip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasvuruTakip</title>



    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />

    <style>
        #bg-video {
            position: fixed;
            right: 0;
            bottom: 0;
            min-width: 100%;
            min-height: 100%;
            z-index: -10;
            object-fit: cover;
            opacity: 0.5;
        }
    </style>
</head>
<body>


 
    <video autoplay muted loop id="bg-video">
        <source src="/videos/background.mp4" type="video/mp4">
    </video>



    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark shadow mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">BasvuruTakip</a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="PersonelIsBasvurusu" asp-action="Create">İş Başvurusu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
                        </li>

                       



                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top text-center text-muted py-3">
        &copy; 2025 - BasvuruTakip
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>